### ISSUE TITLE
afaik readme text was licenses under non disclosure license and subject to dcma

### ISSUE THREAD

**Issue by dzmitry-lahoda** [vix993/rusty_interpreter#1]
right? :)

**Comment by dzmitry-lahoda** [comment]
but if am wrong and somebody else leaked it - do not bother:)

**Comment by vix993** [comment]
I'm confused. What is the issue?

**Comment by dzmitry-lahoda** [comment]
no problem, just was qurious

**Comment by vix993** [comment]
Is it regarding the challenge prompt? I got it for a technical challenge for a job and decided to share my implementation. I can certainly change the readme text if it is obstructing your hiring process.
